#pragma once
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ComfyVersionControl.
//     Time of generation: 2019-08-20 05:56:14
//
//     Manual editing of this file is strongly discouraged.
// <auto-generated>
//------------------------------------------------------------------------------

class BuildVersion
{
public:
	static constexpr const char* Author			= "samyuu";
	static constexpr const char* CommitHash		= "47c72d31e78debc47355112e4305ce13eb1ab9c6";
	static constexpr const char* CommitTime		= "2019-08-19 14:45:04";
	static constexpr const char* CommitCount	= "408";
	static constexpr const char* Branch			= "master";
	static constexpr const char* CompileTime	= "2019-08-20 05:56:14";
};
