#pragma once
#include "Graphics/Direct3D/D3D_Shader.h"

#define DECLARE_BYTECODE_GETTER(shader)	BytecodeBlob shader();
#define DEFINE_BYTECODE_GETTER(shader)	BytecodeBlob shader() { return { ::shader##_Bytecode, sizeof(::shader##_Bytecode) }; }

// NOTE: Public interface
namespace Graphics
{
	DECLARE_BYTECODE_GETTER(ImGui_VS);
	DECLARE_BYTECODE_GETTER(ImGui_PS);

	DECLARE_BYTECODE_GETTER(Sprite_VS);
	DECLARE_BYTECODE_GETTER(Sprite_PS);

	DECLARE_BYTECODE_GETTER(Debug_VS);
	DECLARE_BYTECODE_GETTER(Debug_PS);

	DECLARE_BYTECODE_GETTER(Constant_VS);
	DECLARE_BYTECODE_GETTER(Constant_PS);

	DECLARE_BYTECODE_GETTER(Lambert_VS);
	DECLARE_BYTECODE_GETTER(Lambert_PS);

	DECLARE_BYTECODE_GETTER(BlinnPerVert_VS);
	DECLARE_BYTECODE_GETTER(BlinnPerVert_PS);

	DECLARE_BYTECODE_GETTER(BlinnPerFrag_VS);
	DECLARE_BYTECODE_GETTER(BlinnPerFrag_PS);

	DECLARE_BYTECODE_GETTER(StageBlinn_VS);
	DECLARE_BYTECODE_GETTER(StageBlinn_PS);

	DECLARE_BYTECODE_GETTER(ItemBlinn_VS);
	DECLARE_BYTECODE_GETTER(ItemBlinn_PS);

	DECLARE_BYTECODE_GETTER(SkyDefault_VS);
	DECLARE_BYTECODE_GETTER(SkyDefault_PS);

	DECLARE_BYTECODE_GETTER(Water_VS);
	DECLARE_BYTECODE_GETTER(Water_PS);

	DECLARE_BYTECODE_GETTER(ToneMap_VS);
	DECLARE_BYTECODE_GETTER(ToneMap_PS);
}

// NOTE: Implementation included in the cpp file
#ifdef SHADER_BYTECODE_IMPLEMENTATION

#include SHADER_BYTECODE_FILE(ImGui_VS.h)
#include SHADER_BYTECODE_FILE(ImGui_PS.h)

#include SHADER_BYTECODE_FILE(Sprite_VS.h)
#include SHADER_BYTECODE_FILE(Sprite_PS.h)

#include SHADER_BYTECODE_FILE(Debug_VS.h)
#include SHADER_BYTECODE_FILE(Debug_PS.h)

#include SHADER_BYTECODE_FILE(Constant_VS.h)
#include SHADER_BYTECODE_FILE(Constant_PS.h)

#include SHADER_BYTECODE_FILE(Lambert_VS.h)
#include SHADER_BYTECODE_FILE(Lambert_PS.h)

#include SHADER_BYTECODE_FILE(BlinnPerVert_VS.h)
#include SHADER_BYTECODE_FILE(BlinnPerVert_PS.h)

#include SHADER_BYTECODE_FILE(BlinnPerFrag_VS.h)
#include SHADER_BYTECODE_FILE(BlinnPerFrag_PS.h)

#include SHADER_BYTECODE_FILE(StageBlinn_VS.h)
#include SHADER_BYTECODE_FILE(StageBlinn_PS.h)

#include SHADER_BYTECODE_FILE(ItemBlinn_VS.h)
#include SHADER_BYTECODE_FILE(ItemBlinn_PS.h)

#include SHADER_BYTECODE_FILE(SkyDefault_VS.h)
#include SHADER_BYTECODE_FILE(SkyDefault_PS.h)

#include SHADER_BYTECODE_FILE(Water_VS.h)
#include SHADER_BYTECODE_FILE(Water_PS.h)

#include SHADER_BYTECODE_FILE(ToneMap_VS.h)
#include SHADER_BYTECODE_FILE(ToneMap_PS.h)

namespace Graphics
{
	DEFINE_BYTECODE_GETTER(ImGui_VS);
	DEFINE_BYTECODE_GETTER(ImGui_PS);

	DEFINE_BYTECODE_GETTER(Sprite_VS);
	DEFINE_BYTECODE_GETTER(Sprite_PS);

	DEFINE_BYTECODE_GETTER(Debug_VS);
	DEFINE_BYTECODE_GETTER(Debug_PS);

	DEFINE_BYTECODE_GETTER(Constant_VS);
	DEFINE_BYTECODE_GETTER(Constant_PS);

	DEFINE_BYTECODE_GETTER(Lambert_VS);
	DEFINE_BYTECODE_GETTER(Lambert_PS);

	DEFINE_BYTECODE_GETTER(BlinnPerVert_VS);
	DEFINE_BYTECODE_GETTER(BlinnPerVert_PS);

	DEFINE_BYTECODE_GETTER(BlinnPerFrag_VS);
	DEFINE_BYTECODE_GETTER(BlinnPerFrag_PS);

	DEFINE_BYTECODE_GETTER(StageBlinn_VS);
	DEFINE_BYTECODE_GETTER(StageBlinn_PS);

	DEFINE_BYTECODE_GETTER(ItemBlinn_VS);
	DEFINE_BYTECODE_GETTER(ItemBlinn_PS);

	DEFINE_BYTECODE_GETTER(SkyDefault_VS);
	DEFINE_BYTECODE_GETTER(SkyDefault_PS);

	DEFINE_BYTECODE_GETTER(Water_VS);
	DEFINE_BYTECODE_GETTER(Water_PS);

	DEFINE_BYTECODE_GETTER(ToneMap_VS);
	DEFINE_BYTECODE_GETTER(ToneMap_PS);
}

#endif /* SHADER_BYTECODE_IMPLEMENTATION */
