#define SPRITE_SINGLE_TEXTURE_CHECKERBOARD		0
#define SPRITE_SINGLE_TEXTURE_FONT_BORDER		1
#define SPRITE_SINGLE_TEXTURE_TEXTURE_MASK		0
#define SPRITE_SINGLE_TEXTURE_MULTIPLY_BLEND	0
#include "../Uber/SpriteSingleTexture_Uber.hlsl"
