#pragma once
#include "Types.h"

typedef int32_t KeyState;
enum KeyState_Enum : KeyState
{
	KeyState_Release = 0,
	KeyState_Press = 1,
	KeyState_Repeat = 2,
};

typedef int32_t KeyCode;
enum KeyCode_Enum : KeyCode
{
	KeyCode_Unknown				= -1,

	KeyCode_MouseLeft			= 0x01,
	KeyCode_MouseRight			= 0x02,
	KeyCode_MouseMiddle			= 0x04,
	KeyCode_MouseX1				= 0x05,
	KeyCode_MouseX2				= 0x06,
	KeyCode_Backspace			= 0x08,
	KeyCode_Tab					= 0x09,
	KeyCode_Clear				= 0x0C,
	KeyCode_Enter				= 0x0D,
	KeyCode_Shift				= 0x10,
	KeyCode_Control				= 0x11,
	KeyCode_Alt					= 0x12,
	KeyCode_Pause				= 0x13,
	KeyCode_CapsLock			= 0x14,
	KeyCode_Escape				= 0x1B,
	KeyCode_Space				= 0x20,
	KeyCode_Prior				= 0x21,
	KeyCode_Next				= 0x22,
	KeyCode_End					= 0x23,
	KeyCode_Home				= 0x24,
	KeyCode_Left				= 0x25,
	KeyCode_Up					= 0x26,
	KeyCode_Right				= 0x27,
	KeyCode_Down				= 0x28,
	KeyCode_Select				= 0x29,
	KeyCode_Print				= 0x2A,
	KeyCode_Insert				= 0x2D,
	KeyCode_Delete				= 0x2E,
	KeyCode_Help				= 0x2F,
	KeyCode_0					=  '0',
	KeyCode_1					=  '1',
	KeyCode_2					=  '2',
	KeyCode_3					=  '3',
	KeyCode_4					=  '4',
	KeyCode_5					=  '5',
	KeyCode_6					=  '6',
	KeyCode_7					=  '7',
	KeyCode_8					=  '8',
	KeyCode_9					=  '9',
	KeyCode_A					=  'A',
	KeyCode_B					=  'B',
	KeyCode_C					=  'C',
	KeyCode_D					=  'D',
	KeyCode_E					=  'E',
	KeyCode_F					=  'F',
	KeyCode_G					=  'G',
	KeyCode_H					=  'H',
	KeyCode_I					=  'I',
	KeyCode_J					=  'J',
	KeyCode_K					=  'K',
	KeyCode_L					=  'L',
	KeyCode_M					=  'M',
	KeyCode_N					=  'N',
	KeyCode_O					=  'O',
	KeyCode_P					=  'P',
	KeyCode_Q					=  'Q',
	KeyCode_R					=  'R',
	KeyCode_S					=  'S',
	KeyCode_T					=  'T',
	KeyCode_U					=  'U',
	KeyCode_V					=  'V',
	KeyCode_W					=  'W',
	KeyCode_X					=  'X',
	KeyCode_Y					=  'Y',
	KeyCode_Z					=  'Z',
	KeyCode_LeftWin				= 0x5B,
	KeyCode_RightWin			= 0x5C,
	KeyCode_Apps				= 0x5D,
	KeyCode_Sleep				= 0x5F,
	KeyCode_Numpad0				= 0x60,
	KeyCode_Numpad1				= 0x61,
	KeyCode_Numpad2				= 0x62,
	KeyCode_Numpad3				= 0x63,
	KeyCode_Numpad4				= 0x64,
	KeyCode_Numpad5				= 0x65,
	KeyCode_Numpad6				= 0x66,
	KeyCode_Numpad7				= 0x67,
	KeyCode_Numpad8				= 0x68,
	KeyCode_Numpad9				= 0x69,
	KeyCode_Multiply			= 0x6A,
	KeyCode_Add					= 0x6B,
	KeyCode_Separator			= 0x6C,
	KeyCode_Subtract			= 0x6D,
	KeyCode_Decimal				= 0x6E,
	KeyCode_Divide				= 0x6F,
	KeyCode_F1					= 0x70,
	KeyCode_F2					= 0x71,
	KeyCode_F3					= 0x72,
	KeyCode_F4					= 0x73,
	KeyCode_F5					= 0x74,
	KeyCode_F6					= 0x75,
	KeyCode_F7					= 0x76,
	KeyCode_F8					= 0x77,
	KeyCode_F9					= 0x78,
	KeyCode_F10					= 0x79,
	KeyCode_F11					= 0x7A,
	KeyCode_F12					= 0x7B,
	KeyCode_F13					= 0x7C,
	KeyCode_F14					= 0x7D,
	KeyCode_F15					= 0x7E,
	KeyCode_F16					= 0x7F,
	KeyCode_F17					= 0x80,
	KeyCode_F18					= 0x81,
	KeyCode_F19					= 0x82,
	KeyCode_F20					= 0x83,
	KeyCode_F21					= 0x84,
	KeyCode_F22					= 0x85,
	KeyCode_F23					= 0x86,
	KeyCode_F24					= 0x87,
	KeyCode_NumLock				= 0x90,
	KeyCode_Scroll				= 0x91,
	KeyCode_LeftShift			= 0xA0,
	KeyCode_RightShift			= 0xA1,
	KeyCode_LeftControl			= 0xA2,
	KeyCode_RightControl		= 0xA3,
	KeyCode_LeftAlt				= 0xA4,
	KeyCode_RightAlt			= 0xA5,
	
	KeyCode_Count
};

const char* GetKeyCodeName(const KeyCode keyCode);