#pragma once
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ComfyVersionControl.
//     Time of generation: YYYY-MM-DD HH:MM:SS
//
//     Manual editing of this file is strongly discouraged.
// <auto-generated>
//------------------------------------------------------------------------------

struct Comfy::BuildVersion
{
	static constexpr const char* Author			= "samyuu";
	static constexpr const char* CommitHash		= "0000000000000000000000000000000000000000";
	static constexpr const char* CommitTime		= "YYYY-MM-DD HH:MM:SS";
	static constexpr const char* CommitNumber	= "xxxx";
	static constexpr const char* Branch			= "dummy-branch";
	static constexpr const char* CompileTime	= "YYYY-MM-DD HH:MM:SS";
};
