#pragma once
#include "Graphics/Auth2D/Aet/AetSet.h"
#include <FontIcons.h>

#define ICON_SETLOADER		ICON_FA_FOLDER
#define ICON_TREEVIEW		ICON_FA_LIST
#define ICON_RENDERWINDOW	ICON_FA_TH
#define ICON_INSPECTOR		ICON_FA_INFO_CIRCLE
#define ICON_PROPERTIES		ICON_FA_INFO
#define ICON_TIMELINE		ICON_FA_CLOCK
#define ICON_HISTORY		ICON_FA_HISTORY

#define ICON_NAMES			ICON_FA_LIST
#define ICON_AETCOMPS		ICON_FA_LAYER_GROUP
#define ICON_AETCOMP		ICON_FA_FOLDER
#define ICON_AETCOMP_OPEN	ICON_FA_FOLDER_OPEN
#define ICON_AETVIDEOS		ICON_FA_IMAGES
#define ICON_AETVIDEO		ICON_FA_IMAGE
#define ICON_AETPLACEHOLDER	ICON_FA_EXPAND
#define ICON_AETITEMNONE	ICON_FA_QUESTION_CIRCLE
#define ICON_AETITEMVIDEO	ICON_FA_CUBE
#define ICON_AETITEMAUDIO	ICON_FA_MUSIC
#define ICON_AETITEMCOMP	ICON_FA_CUBES
#define ICON_ANIMATIONDATA	ICON_FA_INFO_CIRCLE
#define ICON_MARKERS		ICON_FA_MAP_MARKER_ALT
#define ICON_PARENT			ICON_AETITEMVIDEO
#define ICON_VISIBLE		ICON_FA_EYE
#define ICON_INVISIBLE		ICON_FA_EYE_SLASH
#define ICON_AUDIBLE		ICON_FA_VOLUME_UP
#define ICON_INAUDIBLE		ICON_FA_VOLUME_MUTE
#define ICON_CAMERA			ICON_FA_VIDEO

#define ICON_ADD			ICON_FA_PLUS
#define ICON_MOVEUP			ICON_FA_ARROW_UP
#define ICON_MOVEDOWN		ICON_FA_ARROW_DOWN
#define ICON_DELETE			ICON_FA_TRASH

namespace Comfy::Studio::Editor
{
	constexpr const char* GetItemTypeIcon(Graphics::Aet::ItemType type)
	{
		switch (type)
		{
		case Graphics::Aet::ItemType::Video:
			return ICON_AETITEMVIDEO;
		case Graphics::Aet::ItemType::Audio:
			return ICON_AETITEMAUDIO;
		case Graphics::Aet::ItemType::Composition:
			return ICON_AETITEMCOMP;
		case Graphics::Aet::ItemType::None:
		default:
			return ICON_AETITEMNONE;
		}
	}
}
